version: '3.8'

services:
  api-nomina:
    build: .
    container_name: api_nomina_prod
    restart: unless-stopped
    environment:
      - TZ=America/Guayaquil
      - SPRING_PROFILES_ACTIVE=prod
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
    networks:
      - web-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      # URL con la que accederás a tu API
      - "traefik.http.routers.api-nomina.rule=Host(`api.fabribat.com`)"
      - "traefik.http.routers.api-nomina.entrypoints=websecure"
      - "traefik.http.routers.api-nomina.tls.certresolver=myresolver"
      # Le decimos a Traefik en qué puerto escucha Spring Boot INTERNAMENTE
      - "traefik.http.services.api-nomina.loadbalancer.server.port=8080"

networks:
  web-network:
    external: true