spring.application.name=apiNomina

# ==========================================
# 1. INTEGRACIÓN CON GOOGLE SECRET MANAGER
# ==========================================
spring.cloud.gcp.project-id=gentle-pier-475304-d0
spring.config.import=sm://gentle-pier-475304-d0

# ==========================================
# 2. BASE DE DATOS 1: PROVEEDOR RRHH (SOLO LECTURA)
# ==========================================
spring.datasource.rrhh.jdbc-url=jdbc:mysql://${sm://MYSQL_G_RRHH_TWIINS_URL}:3306/${sm://MYSQL_G_RRHH_TWIINS_NAMEDB}?useSSL=true&requireSSL=true&trustServerCertificate=true&serverTimezone=America/Guayaquil
spring.datasource.rrhh.username=${sm://MYSQL_G_RRHH_TWIINS_DB_USER}
spring.datasource.rrhh.password=${sm://MYSQL_S_RRHH_TWIINS_PASSWORD}
spring.datasource.rrhh.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# 3. BASE DE DATOS 2: SEGURIDAD GCP (CON SSL ACTIVADO)
# ==========================================
spring.datasource.seguridad.jdbc-url=jdbc:mysql://${sm://MYSQL_G_GCP_PUBLIC_IP}:3306/${sm://MYSQL_G_TI_NAMEDB}?useSSL=true&trustServerCertificate=true&serverTimezone=America/Guayaquil
spring.datasource.seguridad.username=${sm://MYSQL_G_TI_API_RRHH_USER}
spring.datasource.seguridad.password=${sm://MYSQL_S_TI_API_RRHH_PASSWORD}
spring.datasource.seguridad.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# 4. CONFIGURACIÓN GENERAL DEL SERVIDOR
# ==========================================
spring.jpa.open-in-view=false
server.port=8080

# Desactiva la inicializaci�n autom�tica por defecto
spring.sql.init.mode=never

# ==========================================
# 5. CONFIGURACIÓN API ORPHEUS
# ==========================================
orpheus.api.base-url=https://www.bateriasecuador.orpheus2.com.ec/rest
orpheus.api.entidad=47